### PR TITLE
codespell: config, workflow + 1 typo fixed

### PR DESCRIPTION
**Pull request by yarikoptic**
feel welcome to just cherry pick the last commit for the typo fix but thought you might like the rest too

### CODE REVIEW

**Comment by jcupitt** [comment]
LGTM! I'll merge this to my 1.0 branch.

Thank you very much for doing this work, @yarikoptic.

**Review by jcupitt — APPROVED** [review]

**Comment by jcupitt** [comment]
Merged to my main branch here: https://github.com/jcupitt/libdicom

**Comment by fedorov** [comment]
I apologize for not merging this earlier. @yarikoptic thank you for the contribution, and @jcupitt thank you for the review!

**Comment by yarikoptic** [comment]
no problem! thanks for merging! ;)

**Pull request merged**
